name: PlatformHunting
author: Sheigutn
version: 0.0
main: com.gmail.fb020198.Effects.EffectsPlugin
depend: [ProtocolLib, PacketWrapper]

commands:
   corner:
     usage: /<command>
     description: Eckpunkte setzen
   spawnpoint:
     usage: /<command>
     description: Spawnpoint setzen